name: 'Slack Notifier'
description: 'Create and update Slack messages'
inputs:
  channel:
    description: 'The Slack channel to post the message to'
    required: true
  message-id:
    description: 'The Slack message timestamp ID (if updating)'
    required: false
  options:
    description: 'Options for message build'
    required: true
outputs:
  message-id:
    description: 'The Slack message timestamp ID'
runs:
  using: 'docker'
  image: 'Dockerfile'
