name: 'Slack Notifier'
description: 'Create and update Slack messages'
inputs:
  channel:
    description: 'Slack channel'
    required: true
  message-id:
    description: 'Slack message timestamp ID (if updating)'
    required: false
  options:
    description: 'Options for message build'
    required: true
  template:
    description: 'Message template ERB'
    required: false
outputs:
  message-id:
    description: 'The Slack message timestamp ID'
runs:
  using: 'docker'
  image: 'Dockerfile'
