name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Slack Notifier action
      id: slack-notifier
      uses: ./
      with:
        channel: test
