jobs:
  test:
    env:
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Slack Notifier action
      id: slack-notifier
      uses: ./
      with:
        channel: engineering-docker

name: Test

on: [push]
